"use client";
import { useEffect, useState } from "react";
import { browserSupabase, isSupabaseConfigured, missingPublicSupabaseEnv } from "@/lib/supabase";
import { LogOut, Plus, RefreshCw, Save, Trash2 } from "lucide-react";

type Row = Record<string, unknown> & { id?: unknown; name?: string; title?: string; email?: string; status?: string };
const templates: Record<string, Row> = {
  products: { name:"",slug:"",description:"",category:"Rental",price:null,images:[],brochure_url:"",specs:{},featured:false,published:true,sort_order:0 },
  projects: { title:"",slug:"",client:"",location:"",project_type:"",year:new Date().getFullYear(),story:"",gallery:[],testimonial:"",featured:false,published:true },
  site_settings: { id:1,logo_url:"",phone:"",email:"",social_links:{},seo_title:"",seo_description:"",hero_video_url:"" }
};
export function AdminApp(){
  const [session,setSession]=useState<any>(null),[tab,setTab]=useState("products"),[rows,setRows]=useState<Row[]>([]),[editing,setEditing]=useState<Row|null>(null),[message,setMessage]=useState("");
  const configured=isSupabaseConfigured();
  useEffect(()=>{if(!configured)return;const s=browserSupabase();s.auth.getSession().then(x=>setSession(x.data.session));const {data}=s.auth.onAuthStateChange((_e,x)=>setSession(x));return()=>data.subscription.unsubscribe()},[configured]);
  async function request(method="GET",body?:Row,id?:string){const token=session?.access_token;const r=await fetch(`/api/admin/${tab}${id?`?id=${id}`:""}`,{method,headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error);return d}
  async function load(){try{setRows(await request())}catch(e){setMessage((e as Error).message)}}
  useEffect(()=>{if(session)load()},[session,tab]);
  if(!configured){const missing=missingPublicSupabaseEnv();return <AdminShell><div className="mx-auto max-w-xl border border-race p-8"><h1 className="text-3xl font-black uppercase">Connect Supabase</h1><p className="mt-4 text-white/60">The admin panel cannot read the required Supabase environment variables.</p><div className="mt-5 border border-white/10 bg-black p-4 text-sm"><strong>Missing:</strong>{missing.map(x=><code className="mt-2 block text-race" key={x}>{x}</code>)}</div><p className="mt-5 text-sm text-white/50">Confirm the file is named exactly <code>.env.local</code>, then restart <code>npm run dev</code>.</p></div></AdminShell>}
  if(!session)return <AdminShell><Login onDone={setMessage}/></AdminShell>;
  return <AdminShell><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="eyebrow">VORTKART CMS</p><h1 className="text-3xl font-black uppercase">Content control</h1></div><button onClick={()=>browserSupabase().auth.signOut()} title="Sign out"><LogOut/></button></div>
  <div className="mt-8 flex flex-wrap gap-2">{["products","projects","site_settings","inquiries"].map(x=><button key={x} onClick={()=>{setTab(x);setEditing(null)}} className={`px-4 py-2 text-xs font-black uppercase ${tab===x?"bg-race text-black":"border border-white/20"}`}>{x.replace("_"," ")}</button>)}</div>
  <div className="mt-8 flex justify-between"><button onClick={load} title="Refresh"><RefreshCw/></button>{tab!=="inquiries"&&<button onClick={()=>setEditing({...templates[tab]})} className="flex items-center gap-2 bg-race px-4 py-2 text-xs font-black uppercase text-black"><Plus size={16}/> New / Edit settings</button>}</div>
  {message&&<p className="mt-4 text-sm text-race">{message}</p>}
  <div className="mt-6 grid gap-3">{rows.map(r=><div key={String(r.id||r.email)} className="flex items-center justify-between gap-4 border border-white/10 bg-zinc-950 p-4"><div><strong>{String(r.name||r.title||r.email||"Site settings")}</strong><p className="mt-1 text-xs text-white/45">{String(r.category||r.location||r.status||"")}</p></div><div className="flex gap-3"><button onClick={()=>setEditing(r)}>Edit</button>{["products","projects"].includes(tab)&&<button onClick={async()=>{if(confirm("Delete this item?")){await request("DELETE",undefined,String(r.id));load()}}} title="Delete"><Trash2 size={18}/></button>}</div></div>)}</div>
  {editing&&<Editor value={editing} onClose={()=>setEditing(null)} onSave={async value=>{try{await request("POST",value);setEditing(null);setMessage("Saved.");load()}catch(e){setMessage((e as Error).message)}}}/>}</AdminShell>
}
function AdminShell({children}:{children:React.ReactNode}){return <div className="min-h-screen bg-ink px-5 pb-20 pt-28"><div className="mx-auto max-w-6xl">{children}</div></div>}
function Login({onDone}:{onDone:(x:string)=>void}){const [error,setError]=useState(""),[pending,setPending]=useState(false);async function login(fd:FormData){setPending(true);setError("");const {error:authError}=await browserSupabase().auth.signInWithPassword({email:String(fd.get("email")),password:String(fd.get("password"))});setPending(false);if(authError){setError(authError.message);onDone(authError.message)}}return <form action={login} className="mx-auto grid max-w-md gap-4 border border-white/10 bg-zinc-950 p-8"><p className="eyebrow">Secure CMS</p><h1 className="text-3xl font-black uppercase">Admin login</h1><input name="email" type="email" required autoComplete="email" placeholder="Email"/><input name="password" type="password" required autoComplete="current-password" placeholder="Password"/>{error&&<p role="alert" className="border border-red-500/40 bg-red-950/30 p-3 text-sm text-red-300">{error}</p>}<button disabled={pending} className="bg-race p-4 font-black uppercase text-black disabled:opacity-60">{pending?"Signing in...":"Sign in"}</button></form>}
function Editor({value,onClose,onSave}:{value:Row;onClose:()=>void;onSave:(x:Row)=>void}){const [text,setText]=useState(JSON.stringify(value,null,2)),[upload,setUpload]=useState("");async function uploadFile(file:File){const path=`${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const {error}=await browserSupabase().storage.from("media").upload(path,file);if(error)return setUpload(error.message);const {data}=browserSupabase().storage.from("media").getPublicUrl(path);setUpload(data.publicUrl)}return <div className="fixed inset-0 z-[60] overflow-auto bg-black/90 p-5 pt-20"><div className="mx-auto max-w-3xl"><h2 className="text-2xl font-black uppercase">Edit content</h2><p className="my-3 text-sm text-white/50">Upload a media file, then paste its returned URL into the matching JSON field.</p><input type="file" accept="image/*,video/*,.pdf" onChange={e=>e.target.files?.[0]&&uploadFile(e.target.files[0])}/>{upload&&<input className="mt-2" readOnly value={upload} onFocus={e=>e.currentTarget.select()}/>}<textarea className="mt-4 min-h-[55vh] font-mono text-sm" value={text} onChange={e=>setText(e.target.value)}/><div className="mt-4 flex gap-3"><button onClick={()=>{try{onSave(JSON.parse(text))}catch{alert("Invalid JSON")}}} className="flex items-center gap-2 bg-race px-5 py-3 font-black uppercase text-black"><Save size={18}/> Save</button><button onClick={onClose} className="border border-white/20 px-5 py-3 uppercase">Cancel</button></div></div></div>}
